sonar.host.url=https://sonarcloud.io
sonar.organization=sonar-sean-demo
sonar.projectKey=Sonar-Sean-Demo_workshop-python
sonar.projectName=workshop-python

sonar.sources=.
sonar.exclusions=**/migrations/**,**/*.sqlite3,.venv/**

sonar.python.version=3.10,3.11,3.12
sonar.python.coverage.reportPaths=coverage.xml

sonar.sourceEncoding=UTF-8
